### ISSUE TITLE
TypeError: Cannot read property 'from_iterable' of undefined

### ISSUE THREAD

**Issue by KasperKivimaeki** [facebookresearch/hiplot#100]
### Issue
I made a minimalistic React based project that tries to embed Hiplot.

## [My repo](https://github.com/KasperKivimaeki/hiplot-problem)

I followed the instructions in the [documentation: NPM library (javascript)](https://facebookresearch.github.io/hiplot/tuto_javascript.html).

**What happened?**
Installation worked
```bash
$ npm install
```
Starting npm worked
```bash
$ npm start
```
There was an error in my browser
![screenshot](https://raw.githubusercontent.com/KasperKivimaeki/hiplot-problem/master/error.png "screenshot")

**What did you expect to happen?**
I expected to see a website that had Hiplot which would be like in my notebook or like in the pip's Hiplot webserver or in like your demo.

### Goal
I want a website that visualizes my data that is in CSV format with cool looking parallel plots.
I achieved this by using an <iframe /> and a separate Hiplot webserver. 
But the documentation claims that your React component could also work. 

### Thanks
The Hiplot looks amazing and I really appreciate that there is someone maintaining it. Thank you for reading my issue.

**Comment by KasperKivimaeki** [comment]
Problem is caused by both HiPlot and Experiment being undefined after importing.

I don't have enough experience with this stuff. I do not know why importing them causes no errors.

**Comment by danthe3rd** [comment]
Hi @KasperKivimaeki 

Thank you for your report.
The Javascript lib is very recent, and I'm also trying to figure out how to package it the best I can.
I plan to push a new npm package tomorrow - I'll let you know.
Maybe you can try my dev package - do you have the same problem? (`npm install @d3rd/hiplot-dev` and replace `from 'hiplot';` with `from '@d3rd/hiplot-dev';` in your code)

**Comment by KasperKivimaeki** [comment]
Hey @danthe3rd and thank you for quick response.

That did fix the problem and now I have Hiplot on my browser that works.

**Comment by danthe3rd** [comment]
Glad to hear that! So it should be working for you at the next npm package push (tomorrow) - keeping open until then :)

**Comment by danthe3rd** [comment]
Just pushed `0.1.13` on npm, so you should be able to use it again :)
Sorry for the issues - closing
