### ISSUE TITLE
HiPlot not displaying // Version 0.1.14-py3-none-any broken on jupyter notebook

### ISSUE THREAD

**Issue by VectorZhao** [facebookresearch/hiplot#104]
Here is my setup:

OS: Windows 10
browser: Google Chrome 83.0.4103.116 (64 位）
the followings are the errors:
![error](https://user-images.githubusercontent.com/16644993/85921908-40425580-b8b2-11ea-9cf9-1f1199d2c4c4.png)
![error2](https://user-images.githubusercontent.com/16644993/85921912-45070980-b8b2-11ea-9da9-af7600464de5.png)

**Comment by danthe3rd** [comment]
Hi

Thank you for reporting. For some reason this wasn't caught by the CI...
As a workaround, I suggest that you use a previous version (`pip uninstall hiplot` and `pip install hiplot==0.1.12` for instance). I'll publish a fix on monday

**Comment by VectorZhao** [comment]
> Hi
> 
> Thank you for reporting. For some reason this wasn't caught by the CI...
> As a workaround, I suggest that you use a previous version (`pip uninstall hiplot` and `pip install hiplot==0.1.12` for instance). I'll publish a fix on monday

I tried to install version 0.1.12 and hiplot now works. Thank you very much.

**Comment by danthe3rd** [comment]
Closed in `0.1.15`, thank you again for reporting :)
