### ISSUE TITLE
[hiplot 0.1.17] streamlit component demo

### ISSUE THREAD

**Issue by mathematicalmichael** [facebookresearch/hiplot#113]
Tried to follow instructions here: https://facebookresearch.github.io/hiplot/tuto_streamlit.html#tutostreamlit 
but keep hitting

![image](https://user-images.githubusercontent.com/40366263/87447555-f5b22000-c5b7-11ea-90a5-e03cee406f79.png)

when I downloaded the bundle mentioned in the link, and include it, nothing changes. am I putting it in the wrong spot? Or is it referring to a different bundle?

Dockerfile: 
```
FROM python:3.8-slim
RUN pip install -U streamlit
RUN pip install -U hiplot

# lines below have all been experimental to try to debug.
#USER root
# streamlit-specific commands
RUN mkdir -p $HOME/.streamlit
RUN bash -c 'echo -e "\
        [general]\n\
        email = \"\"\n\
        " > $HOME/.streamlit/credentials.toml'
RUN bash -c 'echo -e "\
        [server]\n\
        enableCORS = false\n\
        " > $HOME/.streamlit/config.toml'

COPY hiplot.bundle.js /usr/local/lib/python3.8/site-packages/hiplot/static/built/hiplot.bundle.js
```

**Comment by danthe3rd** [comment]
Hello,

Thank you for the report. Indeed it looks like the built component is not included in the wheel.
Will let you know when it's fixed - hopefully within a few hours

Best

**Comment by danthe3rd** [comment]
Should be fixed in master, and in hiplot >= `0.1.18`.
Leaving it open until 0.1.18 is live :)

**Comment by danthe3rd** [comment]
Version `0.1.18` is live, you can upgrade with `pip install -U hiplot`.
Once again, thank you for reporting and sorry for the inconvenience.
If that works for you, please feel free to close the issue :)

PS: Regarding your tweet (https://twitter.com/COmpMathematics/status/1283069572560547840), testing was disabled because streamlit's public version didn't have support for components, and we couldn't use the closed-beta / non-released version with components on the (public) CI. But you're absolutely right that we should have tested that more...

**Comment by mathematicalmichael** [comment]
@danthe3rd much appreciated. It's an exciting project but it's just far from the first time I got excited about something cool only to find the basic demo not working, so my frustrations aren't solely directed at y'all so much as _the industry_. I am well aware there's a price to pay for early adoption and just keep trying it anyway. 

demo's working now! props to being so quick to push a fix. That's one thing I have definitely noticed about FB's products so far: issues get tackled very quickly.

**Comment by mathematicalmichael** [comment]
out of curiosity... did you take inspiration from this: http://bl.ocks.org/syntagmatic/raw/3150059/ ? Check out the parasol.js library?
source code doesn't look all too similar but the styling does. I only ask because I myself have sunk a ton of effort into good + reusable parallel-plot viz (demo:  dev.mathfight.club).

**Comment by danthe3rd** [comment]
Yes the initial code was largely based on that block (we mention it in our credits: https://github.com/facebookresearch/hiplot#credits) - the example you mention is amazing indeed!

I didn't know about the parasol.js lib, but I'll have a look. Thank you for pointing it out :)
