### ISSUE TITLE
Is it possible to sort the table by a column by default?

### ISSUE THREAD

**Issue by haw230** [facebookresearch/hiplot#118]
I would like to have a certain column in the table sorted in descending order by default without the user clicking on it. Is this possible?

**Comment by danthe3rd** [comment]
Hi :)
No it's not supported yet sadly. I can add that to the next version however - maybe end of august or september.
Thank you for the feedback

**Comment by danthe3rd** [comment]
I've just pushed `0.1.19` (you can upgrade with `pip install -U hiplot`), which adds support for sorting the table by a column by default.
I've updated the documentation with an example (https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings). In short, you can just add this to order by ascending loss:
```
exp.display_data(hip.Displays.TABLE).update({
        # In the table, order rows by default
        'order_by': [['loss', 'asc']]
})
```
It's also possible to sort by multiple columns if you need to
```
exp.display_data(hip.Displays.TABLE).update({
        'order_by': [['col1', 'asc'], ['col2', 'desc']]
})
```
