### ISSUE TITLE
streamlit hiplot continuously rerunning

### ISSUE THREAD

**Issue by DavidWalz** [facebookresearch/hiplot#119]
When using hiplot in streamlit with some random data, the data is regenerated and replotted every ~1s.
```
import numpy as np
import pandas as pd
import hiplot as hip

data = pd.DataFrame(columns=[f"x{i}" for i in range(5)], data=np.random.rand(10, 5))
xp = hip.Experiment.from_dataframe(data)
ret_val = xp.display_st(ret="selected_uids", key="hip")
```

I'm using streamlit version 0.64, and hiplot version 0.1.18.

**Comment by danthe3rd** [comment]
Hi @DavidWalz  and thank you for the report :)
This is related to how streamlit works - every time a component changes its (return) value, the script is re-run. In this case, it will generate different random data, and HiPlot will refresh it.
I would suggest to not use random data in streamlit apps, or to seed the random number generator at the beginning of your script with:
```
np.random.seed(0)
```

I hope this helps

**Comment by DavidWalz** [comment]
Perfect, thanks for the explanation!
