### ISSUE TITLE
The plots are not interactive

### ISSUE THREAD

**Issue by bhishanpdl** [facebookresearch/hiplot#12]
According to this [blog post](https://ai.facebook.com/blog/hiplot-high-dimensional-interactive-plots-made-easy/) I was expecting the plots to be interactive (something like `bqplot` or `plotly` with annotations and highlighting the curve when the cursor touch them)
but in my jupyter notebook the plots are static and there is no interactivity.

How to add the interactivity?

Only `Export `button is highlighted, `Restore`, `Keep`, and `Exclude` button are dim and they can not be clicked.

# Installation
```bash
pip install hiplot
```

# Code
```python
import hiplot as hip
data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam'},
        {'dropout':0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam'}]
hip.Experiment.from_iterable(data).display(force_full_width=True)
```

# output
![](https://i.imgur.com/OBpBZaN.png)

# Comparison to pandas
```python
df = pd.DataFrame(data)
pd.plotting.parallel_coordinates(
        df, 'optimizer',
        color=('#556270', '#4ECDC4', '#C7F464'))
plt.show()
```

# pandas output
![](https://i.imgur.com/yBGFxua.png)

# comparison
Even though `hiplot` is not interactive for me, still its preferable to simple method of pandas parallel plot. HiPlot has better range of values displayed for each coordinates.

# comparison to plotly
```python
import plotly.express as px

data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam'},
        {'dropout':0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam'}]

df = pd.DataFrame(data)

fig = px.parallel_coordinates(df, 
                              color=df['optimizer'].astype('category').cat.codes,
                             color_continuous_scale=px.colors.diverging.Tealrose,
                             color_continuous_midpoint=2)
fig.show()
```

# plotly output
![](https://i.imgur.com/cFybQV3.png)

**Comment by danthe3rd** [comment]
Hi @bhishanpdl and thank you for the detailed bug report and comparisons!

- Can you first provide information about your OS and browser? HiPlot was tested mainly on Firefox/Chrome.
- We've got several feedbacks already that controls are hard to discover, and we're working on this. A `Help` button that triggers a tutorial will be added on the next version.
- [This webpage](https://facebookresearch.github.io/hiplot/_static/demo/demo_basic_usage.html) should be the same experiment you rendered on your notebook.
I made a little video to explain how to slice along axis:

![slicing](https://user-images.githubusercontent.com/43445237/73589357-a1b5f200-44d5-11ea-992c-e3459d4c3163.gif)

- Once you have a non-empty slice of datapoints, you can hit the `Keep` or `Exclude` buttons to select only those
![image](https://user-images.githubusercontent.com/43445237/73589370-d2962700-44d5-11ea-90b1-6832a18bf249.png)

I hope this helps

**Comment by bhishanpdl** [comment]
@danthe3rd I am using MacOS catalina.
```bash
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15.3 (19D76)
      Kernel Version: Darwin 19.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: BpMacpro
      User Name: Bhishan Poudel (Bhishan)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 14:19
```

Browser Tested:  `Google Chrome  Version 79.0.3945.130 (Official Build) (64-bit)`

# Update
I uninstalled the `hiplot` and installed it again. Still it did not worked. Then I suspected there might be some issue with my  `conda` environment. I created a brand new `conda `environment and only installed `hiplot`, then it worked.

Now, its working and I will install other machine learning libraries later, but the good news is I am able to run this awesome library flawlessly.

It's a very helpful visualization library. Especially I liked the interactive selection part. It helps me to select only a few lines and see how the loss value changes for different parameters.

I appreciate Facebook and kudos to devs.

**Comment by danthe3rd** [comment]
Glad you finally got it working!
However I'm curious about what went wrong in the other anaconda env.

Would it be possible for you to do the following in your previous conda environment?
- Send me the output of `conda list --show-channel-urls`
- Run your notebook in the old environment, save it both as "html" and notebook (".ipynb") and upload them
- Send me the content of the javascript console (in chrome's `developper tools`)

Otherwise feel free to close this issue :)
Thank you!

**Comment by bhishanpdl** [comment]
Unfortunately, I had removed conda env, that has problematic hiplot installation and create new conda with same name. So I am unable to reproduce the problem.

The problem is solved and I am closing the issue.
