### ISSUE TITLE
HiPlot citation

### ISSUE THREAD

**Issue by MihailoIsakov** [facebookresearch/hiplot#129]
Hi,

is there a preferred citation for HiPlot,
or should I just cite the blog post? 

Thanks,
Mihailo

**Comment by danthe3rd** [comment]
Hi @MihailoIsakov 

We will come with an official bibtex citation today - will let you know

Thank you for citing HiPlot :)

**Comment by danthe3rd** [comment]
The citation has been added to the README
https://github.com/facebookresearch/hiplot#citing

**Comment by MihailoIsakov** [comment]
Thanks!
