### ISSUE TITLE
Saving Plot

### ISSUE THREAD

**Issue by digantamisra98** [facebookresearch/hiplot#14]
How can I save the plot being rendered in my notebook. 'Export' only saves the data.

**Comment by danthe3rd** [comment]
Hi,

There is currently no way to export the plot as an image (beside making a screenshot). HiPlot focuses more on exploring data rather than making beautiful plots for now.
However, you can retrieve the selected datapoints and plot them with pandas or plotly (issue #12 explains how to do so) - this only works on a Jupyter notebook though.

```python
# Jupyter notebook cell 1:
import hiplot as hip

data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam'},
        {'dropout':0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam'}]
displayed_xp = hip.Experiment.from_iterable(data).display()
```

```python
# Important: must be done in another cell, after the experiment has been displayed
selected_data = [dp.values for dp in displayed_xp.get_selected()]
```

I hope this helps

**Comment by tariksalay** [comment]
This in more advanced, deeper in analysis so it only saves the data instead of image but I am sure soon some devs will figure it out. You might want to use hiplot on top of the other plot libs

**Comment by danthe3rd** [comment]
I'm not sure if I understand exactly what you mean @digantamisra98 by exporting (image? html page?), but another thing that is possible is to export the experiment as a standalone HTML page:
```python
# Jupyter notebook cell 1:
import hiplot as hip

data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam'},
        {'dropout':0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam'}]
hip.Experiment.from_iterable(data).to_html("where/to/render.html")
```
