### ISSUE TITLE
Problem in using hiplot for streamlit

### ISSUE THREAD

**Issue by shangzTJ** [facebookresearch/hiplot#148]
Hi, I tried to run **hiplot/examples/demo_streamlit.py** on Windows , I got the following error in web page:

> Your app is having trouble loading the hiplot.experiment.hiplot component.

> (The app is attempting to load the component from **, and hasn't received its "streamlit:componentReady"** message.)

> If this is a development build, have you started the dev server?
> If this is a release build, have you compiled the frontend?
> For more troubleshooting help, please see the  or visit our ***.

Is this induced by a bug? If not, how can I solve the issue?

Thank you!

**Comment by danthe3rd** [comment]
Hello - and thank you for opening an issue :)

As it's working on my laptop, I would like to check a few things about your setup:
- What is the exact command you typed to run streamlit on this example?
- How did you install hiplot? (with conda? or "pip install" ?)
- Can you run that for me and give me the output? `python -c "import hiplot; print(hiplot.__version__); print(hiplot.__file__)"`

Thank you!

**Comment by shangzTJ** [comment]
Thanks!  @danthe3rd 

1. The command is `streamlit run demo_streamlit.py`, and displayed the following information after the web page was opened
> (base) G:\*** \Vis>streamlit run demo_streamlit.py
>   You can now view your Streamlit app in your browser.
>   Local URL: http://localhost:8501
>   Network URL: http://192.168.1.101:8501
> 
> 2021-01-16 23:18:53.428 Uncaught exception GET /component/hiplot.experiment.hiplot/hiplot_streamlit.bundle.js (::1)
> HTTPServerRequest(protocol='http', host='localhost:8501', method='GET', uri='/component/hiplot.experiment.hiplot/hiplot_streamlit.bundle.js', version='HTTP/1.1', remote_ip='::1')
> Traceback (most recent call last):
>   File "c:\programdata\anaconda3\lib\site-packages\tornado\web.py", line 1697, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "C:\**\AppData\Roaming\Python\Python37\site-packages\streamlit\components\v1\components.py", line 324, in get
>     contents = file.read()
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 271327: illegal multibyte sequence
> 2021-01-16 23:18:53.439 500 GET /component/hiplot.experiment.hiplot/hiplot_streamlit.bundle.js (::1) 246.86ms

2. Hiplot is installed with `pip install`

3. The output is 
`0.1.22
C:\Users\**\AppData\Roaming\Python\Python37\site-packages\hiplot\__init__.py
`

**Comment by danthe3rd** [comment]
Oh I see.
It's the same issue as in https://github.com/facebookresearch/hiplot/issues/127. I proposed a workaround in the issue - but it's a problem within streamlit - tracking in https://github.com/streamlit/streamlit/issues/1936

**Comment by shangzTJ** [comment]
It works. Thank you :) @danthe3rd

**Comment by danthe3rd** [comment]
This should be fixed in streamlit as of the next release (or with streamlit-nightly)
https://github.com/streamlit/streamlit/issues/1936#issuecomment-794593002
