### ISSUE TITLE
Integration possible with Streamlit?

### ISSUE THREAD

**Issue by thomwolf** [facebookresearch/hiplot#15]
Hi all,
This is a really awesome project! Thanks a lot for open-sourcing it.

Given the Jupiter notebook integration, I was wondering if integration with streamlit with possible.

You may know [streamlit](https://github.com/streamlit/streamlit/) which is kinda like a Jupyter notebook but with advantages like full python compatibility, a clean hidden state (script always run in order and smart caching) and an easy transition to production (see for instance this [introductory blog post](https://towardsdatascience.com/coding-ml-tools-like-you-code-ml-models-ddba3357eace)).

It would be nice to be able to use the interactive plots of HiPlot in a streamlit script, do you think this is possible?

**Comment by danthe3rd** [comment]
Hi @thomwolf 

I wasn't aware of streamlit before, but it looks like a great synergy for HiPlot!
HiPlot should work out of the box with others notebook-like interfaces (Jupyter lab...) although this hasn't been the main focus. So it might even work with streamlit already...?

But I assume you want to be able to only use the parallel plot for instance, or chain HiPlot with other things like
```
selected_rows = hiplot_experiment.display()
my_custom_plots(selected_rows)
```

I'm not sure what it takes exactly to achieve that, but I'll take a look at it when I get some bandwidth :)

**Comment by danthe3rd** [comment]
Hi

Support for (incoming) Streamlit components has landed in master.
Please check the doc (https://facebookresearch.github.io/hiplot/tuto_streamlit.html), and send me a PM in the streamlit forum if you would like to beta-test it - so I can send you the streamlit wheel with components support.

reopening, until components support lands in streamlit.

**Comment by danthe3rd** [comment]
Streamlit officially released components, so hiplot now works on Streamlit apps!
https://mobile.twitter.com/facebookai/status/1283057821433516032
