### ISSUE TITLE
The React module crashes in a dev server 

### ISSUE THREAD

**Issue by ssine** [facebookresearch/hiplot#150]
Hi there, thanks for open-sourcing this amazing project firstly.

I tried out the [react npm package](https://www.npmjs.com/package/hiplot), however the page crashes in browser with error like this:

```text
×
TypeError: Cannot read property 'call' of undefined
__webpack_require__
E:/tmp/hiplot/my-app/node_modules/hiplot/dist/hiplot.lib.js:36
  33 | /******/ 		};
  34 | /******/
  35 | /******/ 		// Execute the module function
> 36 | /******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
  37 | /******/
  38 | /******/ 		// Flag the module as loaded
  39 | /******/ 		module.l = true;
View compiled
(anonymous function)
E:/tmp/hiplot/my-app/node_modules/hiplot/dist/hiplot.lib.js:43836
  43833 | })(
  43834 |   this,
  43835 |    true && module,    // present in node.js
> 43836 |   (typeof define) == 'function' && define   // present with an AMD loader
  43837 | );
  43838 | 
  43839 | 
View compiled
(anonymous function)
E:/tmp/hiplot/my-app/node_modules/hiplot/dist/hiplot.lib.js:43841
  43838 | 
  43839 | 
  43840 | 
> 43841 | /* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(5)(module)))
  43842 | 
  43843 | /***/ }),
  43844 | /* 19 */
View compiled
__webpack_require__
E:/tmp/hiplot/my-app/node_modules/hiplot/dist/hiplot.lib.js:36
  33 | /******/ 		};
  34 | /******/
  35 | /******/ 		// Execute the module function
> 36 | /******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
  37 | /******/
  38 | /******/ 		// Flag the module as loaded
  39 | /******/ 		module.l = true;
```

Note that the error only appears in a development server, a production mode build works fine.

## How to reproduce

The setup just follows the [official react template](https://reactjs.org/docs/create-a-new-react-app.html):

```bash
npx create-react-app my-app
cd my-app
npm install hiplot -S
# add the basic example to App.js ...
npm start
```

I searched around and none of the answers works (on "my-app" level), maybe we need some changes in webpack building of hiplot?

Thanks!

**Comment by danthe3rd** [comment]
Hi @ssine  and thanks for the (detailed) report :)

I can indeed repro - there is a lot of black magic going on with the different bundlers / webpack / packages...
The example for the docs is building (see https://github.com/facebookresearch/hiplot/tree/master/examples/javascript), but not the basic one created by `create-react-app`. I'll have a look

Thank you

**Comment by danthe3rd** [comment]
I just published an update that should fix it :)
You can `npm install hiplot@latest `. Closing - please re-open if there is still an issue

**Comment by ssine** [comment]
It's working now, Thanks!
