### ISSUE TITLE
Streamlit: Weird characters in places / Encoding issue on Windows?

### ISSUE THREAD

**Issue by F1nnM** [facebookresearch/hiplot#160]
Hi!
This issue only happens Windows, it seems fine in my Linux-Docker-Containers.
In the top left corner of the Streamlit component there is an Â, whereas in Linux there is only a invisible whitespace:
![A in corner](https://i.ibb.co/mTNB5q1/grafik.png)
Also the arrows in the table header are displayed incorrectly:
![Arrows displayed wrong](https://i.ibb.co/fXgY74V/grafik.png)

It might be an encoding issue with Streamlit, or you might be able to fix that on your side, I'm not sure.

**Comment by danthe3rd** [comment]
Streamlit does not specify the encoding of the static files for components, so a lot of weird things happen :/
See https://github.com/streamlit/streamlit/issues/1936
Unfortunately, there is not a lot I can do on the HiPlot side

**Comment by F1nnM** [comment]
Ah alright. Thanks for the info. Well, we'll have to wait until they fix it then.
