### ISSUE TITLE
No context menu on right click

### ISSUE THREAD

**Issue by ssine** [facebookresearch/hiplot#163]
It seems that the right click context menu isn't working for the npm module:

![image](https://user-images.githubusercontent.com/20841764/107136838-98a9fd00-6941-11eb-96f7-82ccd97a9b8e.png)

The browser right click menu was displayed, same under both MacOS and Win10, Chrome.

**Comment by danthe3rd** [comment]
Hi, and thank you for your feedback :)

For the contextual menu, you should right-click the column title, and not inside the parallel plot
![image](https://user-images.githubusercontent.com/43445237/107196208-9fdd1380-69f2-11eb-9d5c-6e9a9b51b0c0.png)

Let me know if that works

**Comment by ssine** [comment]
Oh yes it works, it's surprising that I didn't even think about clicking on title🤣 thanks
