### ISSUE TITLE
Streamlit: Export Button doesn't work

### ISSUE THREAD

**Issue by F1nnM** [facebookresearch/hiplot#169]
I use the Hiplot-Component in Streamlit. When I click the Export button nothing happens. No download starts, no error in the console, no log on the server.

**Comment by F1nnM** [comment]
Hi, any news on this?
If not, no problem, just curious.

**Comment by danthe3rd** [comment]
Hi,

Just tried it and indeed it's blocked.
It looks like a security feature from Streamlit (Streamlit components run inside an HTML iframe).
From Chrome logs:
> Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.

This is the code for the iframe (which indeed does not include `allow-downloads`):
```html
<iframe
allow="accelerometer; ambient-light-sensor; autoplay; battery; camera; document-domain; encrypted-media; fullscreen; geolocation; gyroscope; layout-animations; legacy-image-formats; magnetometer; microphone; midi; oversized-images; payment; picture-in-picture; publickey-credentials-get; sync-xhr; usb; vr ; wake-lock; xr-spatial-tracking" 
src="http://localhost:8501/component/hiplot.streamlit_helpers.hiplot/index.html?streamlitUrl=http%3A%2F%2Flocalhost%3A8501%2F" 
width="698" 
height="949" 
scrolling="no" 
sandbox="allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts" 
title="hiplot.streamlit_helpers.hiplot"></iframe>
```

So it's not really something I can fix from HiPlot's side (I can maybe remove the button tho).

**Comment by F1nnM** [comment]
Interesting, in Firefox I didn't get any errors at all. 
Please don't remove the button, I think it's a very useful feature - if it works. I'll open an issue at the Streamlit repository, and we'll see whether they fix this.

**Comment by F1nnM** [comment]
Update: My PR over there was accepted. So once the next version is released, the export button should work.

**Comment by danthe3rd** [comment]
Oh great news! Thanks for getting it done :)

**Comment by F1nnM** [comment]
https://github.com/streamlit/streamlit/releases/tag/0.80.0
New version is out and the dowload button works flawlessly.

**Comment by danthe3rd** [comment]
Nice! Thanks for taking care of it :)
