### ISSUE TITLE
Issue with range of parallel plot axes

### ISSUE THREAD

**Issue by F1nnM** [facebookresearch/hiplot#170]
I use the Streamlit component. When I load a page with a certain dataset the autoscaling of the axes causes some valaues to be outside the scale.
![](https://i.ibb.co/mBZrVdY/grafik.png)
As soon as I update the plot, selecting and excluding a row the scaling updates to the correct one:
![](https://i.ibb.co/QFdhvpw/grafik.png)
I don't understand whats going on. I don't think, it's an issue on my side, because I'm not doing any manual scaling of the axes.

**Comment by danthe3rd** [comment]
hi @F1nnM  and thanks for reporting

This is very weird, I never experienced something like that :o
Is it always happening to the same column? Are you doing something in particular with this column?

**Comment by F1nnM** [comment]
It's only that column, I'm not doing anything to it that I wouldn't do the others.
It happens every time with this dataset, with this exact column.
Loading this dataset concatted with other datasets, it doesn't happen.

**Comment by danthe3rd** [comment]
is it possible for you to export this dataset so I can reproduce it? For instance using `experiment.to_csv("/path/to/file.csv")`
Otherwise - if you can't share the dataset - I'm also curious to see if you can reproduce it outside streamlit (`experiment.to_html("/path/to/file.html")`)

**Comment by F1nnM** [comment]
I'm afraid, I can't give you the dataset. I can reproduce it outside streamlit.
My data is read from a database. Exporting the data, and importing it again fixes it.
I now have two identical datasets, where one causes the bug and one doesn't.

**Comment by F1nnM** [comment]
So I now replaced the one table that causes the bug with the copy that doesn't and by that "fixed" any issues I had. 
I am confused as to why it behaves like that, but I guess so are you.
I don't need this to be fixed anymore and I doubt it can be fixed.
