### ISSUE TITLE
Colormap: colormap that centered on zero

### ISSUE THREAD

**Issue by wuzhe1234** [facebookresearch/hiplot#173]
Is there any way have a centered on zero colormap?

**Comment by danthe3rd** [comment]
Hi @wuzhe1234 

We use the same scale for the colormap as for the data. So should be able to do something like that:
```python
import hiplot as hip

# Create experiment as usual
column = "metric"
maximum_abs = max(abs(dp.values.get(column, 0)) for dp in experiment.datapoints)
experiment.parameters_definition[column] = ValueDef(type=hip.ValueType.NUMERIC).force_range(minimum=maximum_abs, maximum=-maximum_abs)

# Display experiment as usual
```

**Comment by wuzhe1234** [comment]
> Hi @wuzhe1234
> 
> We use the same scale for the colormap as for the data. So should be able to do something like that:
> 
> ```python
> import hiplot as hip
> 
> # Create experiment as usual
> column = "metric"
> maximum_abs = max(abs(dp.values.get(column, 0)) for dp in experiment.datapoints)
> experiment.parameters_definition[column] = ValueDef(type=hip.ValueType.NUMERIC).force_range(minimum=maximum_abs, maximum=-maximum_abs)
> 
> # Display experiment as usual
> ```

Thank you, problem solved!  I use "hip.ValueDef(value_type=hip.ValueType.NUMERIC)" instead of  "hip.ValueDef(type=hip.ValueType.NUMERIC)" to make it work.

Best Regards.
