### ISSUE TITLE
Colormap: reverse a d3.js colomap

### ISSUE THREAD

**Issue by wuzhe1234** [facebookresearch/hiplot#174]
How to reverse a d3.js colormap in hiplot? For example, change "interpolateRdBu" to " interpolateBuRd"

**Comment by danthe3rd** [comment]
Hi @wuzhe1234 

It's not currently possible. I've created #175 that will allow it once landed.

Best

**Comment by danthe3rd** [comment]
Version `0.1.24` has been published :)
Please install it (`pip install -U hiplot`) and you should be able to use `interpolateRdBu#inverse` as a colormap
