### ISSUE TITLE
hip.Experiment.from_iterable adds additional uid column

### ISSUE THREAD

**Issue by qo4on** [facebookresearch/hiplot#183]
In your Colab example `hip.Experiment.from_iterable` adds additional `uid` column. Is it possible to remove it?

![image](https://user-images.githubusercontent.com/35609308/116124413-b59ed280-a6dd-11eb-9c59-380d7c6f3c97.png)

**Comment by danthe3rd** [comment]
Hi
Yes indeed that's something that has come up a lot, and your solution is the right way to fix it for now. It's useful to identify rows uniquely - but for basic use-cases it makes it less clear.
I'm thinking about hiding it by default if not specified in the source data.
