### ISSUE TITLE
Color Gradient

### ISSUE THREAD

**Issue by qo4on** [facebookresearch/hiplot#186]
Is it possible to set color gradient (for example from blue to red according to axis values) instead of random colors?

![image](https://user-images.githubusercontent.com/35609308/116442336-d137e380-a86b-11eb-97cb-151e4be58f4a.png)

**Comment by danthe3rd** [comment]
Hi @qo4on 
You can do several things:
1. Chose which column you want to color by (right click on the column name -> Color by)
2. Change the Colormap used with `experiment.colormap = "schemeYlOrRd"` (the colormap names are from https://github.com/d3/d3-scale-chromatic)

I hope that helps :)

**Comment by qo4on** [comment]
Thank you. Unfortunately most of the gradient color schemes there have white or low saturated colors which are not very visible. It would be better to set simple 2 or 3 color gradient based on rgb values and set which color to be on top when overlapping.

**Comment by danthe3rd** [comment]
Thanks for the feedback, that's very true - I'll try to improve that in the future.
In the meantime, I think `interpolatePlasma` is the closest to the image you posted initially.
