### ISSUE TITLE
requirements/{dev,main}.txt are not included in sdist

### ISSUE THREAD

**Issue by sunpoet** [facebookresearch/hiplot#19]
[setup.py](https://github.com/facebookresearch/hiplot/blob/master/setup.py#L16-L18) reads requirements/{dev,main}.txt for install_requires and extras_require. But these two files are not included in the 1.0.3 sdist.

**Comment by danthe3rd** [comment]
Fixed in `0.1.4`

**Comment by sunpoet** [comment]
Thanks!
