### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by bensdm** [facebookresearch/hiplot#20]
Thanks for this amazing tool.
I am running it as a server but I am not able to export as expected the output of my filters.
When i click export it is opening me a new tab with the csv txt but i am not able to save this as a csv.
The saved file looks like
![image](https://user-images.githubusercontent.com/29406515/73988770-4f2b6a00-4909-11ea-9f8a-3b264d6a0d3b.png)

Am i doing anything wrong? 
Would be a lot of time saved i there was an other way than copy paste
Thanks

**Comment by danthe3rd** [comment]
Hi and thank you for the bug report!  :)
The "export" button will now download a CSV file directly (added in `0.1.4`).

**Comment by bensdm** [comment]
thanks for the fix, do you think it would be possible to specify the folder where we want to save it?
