### ISSUE TITLE
Notebook displayed visualization interaction doesn't work due to misregistered callback

### ISSUE THREAD

**Issue by limwenbin** [facebookresearch/hiplot#202]
Methods like displayed_exp.get_selected() and displayed_exp.get_brush_extents() don't work in the jupyter notebook because the messages are not being sent from the javascript end.

Problem seems to be with the callbacks being registered to the name "on_change" instead of "onChange" at https://github.com/facebookresearch/hiplot/blob/master/hiplot/ipython.py#L156. Changing that seems to fix it on my end.

**Comment by danthe3rd** [comment]
Oh that's right, nice catch!
Do you want to open a pull-request? Otherwise I can fix it next week

**Comment by limwenbin** [comment]
Thank you that would be a great help since I'm not CLA-ed + I haven't ran the test suite. Very cool library by the way. The plot is already pretty sweet but being able interactively access the selection is a game changer for my workflow.

**Comment by danthe3rd** [comment]
> CLA-ed + I haven't ran the test suite

The tests run on the CI when you submit your pull-request, and a bot will help you get CLA-ed (I think you just have to accept some conditions). But I can do it otherwise :)
