### ISSUE TITLE
Hiding the entire table / Reducing the number of rows to as low as 1 / adjusting table height similar to the parallel plots

### ISSUE THREAD

**Issue by srijandidwania** [facebookresearch/hiplot#229]
Hello,
Hiplot is a great tool. I was looking to see if there is a way or plan for enhancement to allow user do any of the following. All are intended to facilitate hidingg / reducing the size of table at the bottom if desired by user.

1) Option / code to Hide the entire table from the HiPlot display.
2) Currently there is a drop down to select number of rows with minimum being 10, Can there be one more entry of 1 to show minimum number of rows?
3) There is a drag feature to modify the height of parallel plot display. Can there be any functionality to ad the same to the table.

Thanks!

**Comment by danthe3rd** [comment]
Hello,

Thanks for the feedback on HiPlot :)

First, how do you use HiPlot (webserver, generating HTML files, in a notebook, with streamlit etc..)?
I'm wondering why you want to hide the table (is it taking too much space?). In any case, option (1) (having the ability to remove the table alltogether) seems to be the best solution to implement for your question. 

Thanks

**Comment by srijandidwania** [comment]
Thanks for quick response. I understand it might get implemented in the future.

I use it with HTML and streamlit mostly. Sometimes I want to add other custom graphs at the bottom and wish we can see both of them together on the same screen rather than scrolling down. Therefore I was thinking if there is a feature to hide the table it could be really helpful in that respect.

Thanks!

**Comment by danthe3rd** [comment]
I just merged a PR that should address it. You can remove the table with the following code:
```python
experiment.enabledDisplays.remove(hip.Displays.TABLE)
```

This will be added in the next hiplot version (`0.1.33`). In the meantime, you can use the pre-release version with `pip install -U --pre hiplot`

**Comment by srijandidwania** [comment]
> I just merged a PR that should address it. You can remove the table with the following code:
> 
> ```python
> experiment.enabledDisplays.remove(hip.Displays.TABLE)
> ```
> 
> This will be added in the next hiplot version (`0.1.33`). In the meantime, you can use the pre-release version with `pip install -U --pre hiplot`

That is Fantastic. Thanks!
