### ISSUE TITLE
Exporting as a standalone html

### ISSUE THREAD

**Issue by mojovski** [facebookresearch/hiplot#23]
Hi there, 
thanks for the super awesome tool! I am deeply impressed by your work!

I saw some notes, that there is a way to export a plot as an interactive standalone html code.
Could you elaborate on it a little bit?

Thanks a lot!!

**Comment by danthe3rd** [comment]
Hi :)

There are 2 ways. Either from python with the `to_html` method (https://facebookresearch.github.io/hiplot/py_reference.html#hiplot-experiment), or from the cli (see https://facebookresearch.github.io/hiplot/tuto_webserver.html#dump-your-experiments-to-csv-or-html-with-hiplot-render)

I hope this helps :)

**Comment by mojovski** [comment]
Thanks! It works like described.

**Comment by Pritsam** [comment]
Is there any way to make changes to styling of the generated HTML. Such as reducing font size, removing the header etc.

**Comment by danthe3rd** [comment]
Hi @Pritsam 
This is not supported in HiPlot unfortunately. If you want to reduce the font size, it might be possible by injecting some CSS. For removing the header, I suppose you would have to do that by removing it from the HTML page manually ...

**Comment by Pritsam** [comment]
Thanks for the information. But I think including this feature would be really helpful for making some styling customizations.
