### ISSUE TITLE
Add hiplot exampel to optuna/optuna-examples

### ISSUE THREAD

**Issue by nzw0301** [facebookresearch/hiplot#235]
Hi, 

As mentioned in https://github.com/facebookresearch/hiplot/pull/216#issuecomment-948703483 before, we plan to add a hiplot example to optuna's example repo as in this PR https://github.com/optuna/optuna-examples/pull/86.

Even though the example uses a simple API `hiplot.Experiment.from_optuna(study).display()`, I'm wondering if we could get some feedback from the hiplot community. 

Maybe linking to two notebooks using Optuna in https://github.com/facebookresearch/hiplot/tree/main/examples from the hiplot example's notebook might be useful.

Best regards,

**Comment by danthe3rd** [comment]
Hi @nzw0301,

I'm happy to see HiPlot integrated in the official optuna examples repo :)
The PR https://github.com/optuna/optuna-examples/pull/86 looks great to me. Maybe we can add some link to hiplot's documentation (more specifically the [rendering section where we explain how things can be customized](https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings) ), but other than that it looks good to me!

Best

**Comment by nzw0301** [comment]
The PR has been merged into Optuna's example repo. Again, thank you for your feedback!
