### ISSUE TITLE
Hiplot custom button

### ISSUE THREAD

**Issue by namikisik** [facebookresearch/hiplot#238]
I'd like to add a button to Hiplot in order to trigger a python function. In my case, the function will visualize the Hiplot exported csv file with dash interactive cross-filtering.

**Comment by danthe3rd** [comment]
Hi @namikisik 

The proper solution to what you are requesting is the Dash integration of HiPlot (see this issue https://github.com/facebookresearch/hiplot/issues/194).

If you are using a Jupyter notebook, you can achieve something similar in the meantime - see the doc section [Interactions with displayed visualization](https://facebookresearch.github.io/hiplot/tuto_notebook.html#interactions-with-displayed-visualization). In your first notebook cell, you render your hiplot experiment, and in a second cell you can retrieve currently selected rows, and filter them through Dash (or anything else). You can then re-execute the second notebook cell to refresh the Dash display with your currently selected rows.

I hope this helps

**Comment by namikisik** [comment]
Hi @danthe3rd,
I am already coming from the issue #194. At the other hand, thanks for the recommendation, I'll definitely check it.
