### ISSUE TITLE
Unable to start webserver as per docs

### ISSUE THREAD

**Issue by alexjj** [facebookresearch/hiplot#24]
I like parallel coordinate plots and was interested to try out hiplot.

The docs state starting the webserver as:

`>>> hiplot`

i.e. from a python prompt. When I try it just outputs:
`<module 'hiplot' from 'C:\\Users\\ajohnstone\\AppData\\Local\\Continuum\\anaconda3\\envs\\visuals\\lib\\site-packages\\hiplot\\__init__.py'>` and there's no server running. 

I see there's a function `run_server_main()`, and so running `hiplot.run_server_main()` from the python prompt then starts the web server.

**Comment by danthe3rd** [comment]
Hi @alexjj 

The `hiplot` command is a command-line script. You should run it from a terminal, not from the python terminal.
If you have a python terminal open, you should use `run_server_main` (https://facebookresearch.github.io/hiplot/py_reference.html#hiplot.run_server).

Best

**Comment by alexjj** [comment]
Okay. Perhaps change the prompt to be `$` instead of `>>>`?

**Comment by KVSSetty** [comment]
when I try to use hiplot as the webserver got the error:

(hiplotenv) C:\Users\kvsse>hiplot
'hiplot' is not recognized as an internal or external command,
operable program or batch file.

but works in notebook

**Comment by KVSSetty** [comment]
Tried this still no severe running:


(hiplotenv) C:\Users\kvsse>hiplot
'hiplot' is not recognized as an internal or external command,
operable program or batch file.

(hiplotenv) C:\Users\kvsse>python
Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:30:06) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> hiplot.run_server_main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'hiplot' is not defined

(hiplotenv) C:\Users\kvsse>hiplot
'hiplot' is not recognized as an internal or external command,
operable program or batch file.

(hiplotenv) C:\Users\kvsse>python
Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:30:06) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> hiplot.run_server_main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'hiplot' is not defined

 hiplot.run_server_main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'hiplot' is not defined

**Comment by danthe3rd** [comment]
Hi @KVSSetty ,

This will be fixed in the next hiplot version. In the meantime, you can use `python -m hiplot` as a workaround
