### ISSUE TITLE
Provide ability to define custom ordering for categorical variables

### ISSUE THREAD

**Issue by sudeepag** [facebookresearch/hiplot#246]
It would be great if there was a way to define a custom ordering for categorical variables, or at least an ascending / descending option. I noticed that clicking on the label reverses it, but providing a way to customize the ordering would be very helpful.

**Comment by danthe3rd** [comment]
Hi @sudeepag and thanks for your feedback :)

Do you have an example for what type of custom ordering you would like to have?

Thanks

**Comment by danthe3rd** [comment]
You can do this to invert the column default order - is it what you are looking for?
I believe categorical values will be ordered alphabetically by default
```
    exp.display_data(hip.Displays. PARALLEL_PLOT).update({
        'invert': ['my_col_name'],
    })
```
