### ISSUE TITLE
Problems exploring demo examples

### ISSUE THREAD

**Issue by algarji** [facebookresearch/hiplot#252]
I am exploring the GSEA advanced module through the website (https://hiplot-academic.com/advance/gsea) and I would like to understand which is the exact format of the input data. However, when I load the demo data and try to download or visualize the inputs (e.g. public/demo/gsea/P53.txt) an error or a blank page appeared. Is it possible to get access to these files? Thank you.

**Comment by GoldenCorgi** [comment]
Hello! I believe your tutorial is from a different package/website from this repository, you should get better answers if you redirect your query to GSEA instead
