### ISSUE TITLE
How to modify the scale of axis?

### ISSUE THREAD

**Issue by rrrgggccc** [facebookresearch/hiplot#256]
Hello! I wonder how to fix all feature scales as [0,1]. Is it possible to achieve that? Many thanks.
![image](https://user-images.githubusercontent.com/115540599/195052252-0dc99fab-dd5a-4e8c-a9ae-72f21030e679.png)

**Comment by danthe3rd** [comment]
Hi @rrrgggccc 

You can force a minimum/maximum value for arbitrary features - [see the corresponding doc](https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings). Something like that should work for you
```python
exp.parameters_definition["mbsc"].force_range(0, 1)
```

**Comment by rrrgggccc** [comment]
Thank u so much for your kind help!
