### ISSUE TITLE
Integratable hiplot results as a React component?

### ISSUE THREAD

**Issue by mojovski** [facebookresearch/hiplot#27]
Hi,
I would like to use the awesome hiplot results for a React-based blog (Gatsby).
However, integration of the fully standalone HTML page requires iframes (my current stand of knowledge).

So it would be great to have a React component, which can take the JSON generated by the python hiplot module.

I guess, you are using react components inside the framework anyway. But are there also plans to extract them for 3rd party integration?

Thanks a lot!

**Comment by danthe3rd** [comment]
> Hi,
> I would like to use the awesome hiplot results for a React-based blog (Gatsby).
> However, integration of the fully standalone HTML page requires iframes (my current stand of knowledge).

That is correct - this is how HiPlot is rendered on Jupyter notebooks, as well as on our [documentation website](https://facebookresearch.github.io/hiplot/).


> So it would be great to have a React component, which can take the JSON generated by the python hiplot module.
> I guess, you are using react components inside the framework anyway. But are there also plans to extract them for 3rd party integration?

HiPlot also has a [NPM package](https://www.npmjs.com/package/hiplot), which contains the overall `HiPlot` component.

**However**, as you have noticed this is not documented yet, not really tested in that setting (I think all the component will have a width of 100% the width of the screen, might update the URL to remember the settings - which will create conflict with 2 hiplots on the same page, and other bad surprises). Being able to use HiPlot as a React component is definitively on my todo list, and I might break the React API at this point as well.


If you still want to use it, you can check [this example](https://github.com/facebookresearch/hiplot/blob/980795350109601834d8e9014d6b0b6804bb4f4f/src/hiplot.tsx#L366-L379).
In the props, you should set `experiment` to something corresponding to the JSON serialization of your `hip.Experiment`: `json.dumps(my_xp._asdict())`. You should also set `is_webserver` to false.

**Comment by mojovski** [comment]
Thank you! I think I will rather go with an iframe as of today. Need multiple hiplots in one page etc
