### ISSUE TITLE
[Bug] Getting a weird error by making the experiment a variable then calling display 

### ISSUE THREAD

**Issue by mike-leuer-callaway-golf** [facebookresearch/hiplot#271]
This works fine
```
data = [{'uid': 'a', 'dropout': 0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD', 'x': x1},
        {'uid': 'b', 'dropout': 0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam', 'x': x2},
        {'uid': 'c', 'dropout': 0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam', 'x': x3}]
d = hip.Experiment.from_iterable(data).display()
```
![image](https://user-images.githubusercontent.com/97471415/210633992-061adcb5-75dc-436c-8d65-be29c7fd4bb4.png)

However this does not work see screen shot
```
data = [{'uid': 'a', 'dropout': 0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD', 'x': x1},
        {'uid': 'b', 'dropout': 0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam', 'x': x2},
        {'uid': 'c', 'dropout': 0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam', 'x': x3}]
d = hip.Experiment.from_iterable(data)
d.display()
```
![image](https://user-images.githubusercontent.com/97471415/210633893-252ce951-c921-425c-8d49-29b8797e7a13.png)

**Comment by mike-leuer-callaway-golf** [comment]
Using Mircosoft Machine Learning Studio 
https://learn.microsoft.com/en-us/azure/machine-learning/overview-what-is-azure-machine-learning

**Comment by danthe3rd** [comment]
Hi @mike-leuer-callaway-golf 
That's a very weird bug indeed. Both of your examples are working fine for me on a Google Collab, it seems more likely to be a bug within your notebook system at this point. As a workaround, you can try maybe the following:
```python
d = hip.Experiment.from_iterable(data)
_ = d.display()
```

**Comment by mike-leuer-callaway-golf** [comment]
Wow that fixes it. Do you have any idea why that is? (More of a programmers curiosity)

**Comment by danthe3rd** [comment]
I'm not exactly sure actually. One difference between your 2 cases was that in the first one, the notebook should output something like:
```
(hiplot widget)
<hiplot.ipython.IPythonExperimentDisplayed at 0x7ff61f198970>
```

But if you have an assignment, it does not display any variable (just the hiplot widget). I believe this was the main issue with your notebook system from Azure.
So it's definitively a bug with the Azure notebook.

**Comment by mike-leuer-callaway-golf** [comment]
Thank you for the help. Hopefully this helps the next person who uses azure notebooks.
