### ISSUE TITLE
Text parameters are not shown in the html

### ISSUE THREAD

**Issue by praksharma** [facebookresearch/hiplot#278]
I am using version 0.1.33. I am struggling to display text parameter such as activation, architecture on exported html file. however the parameters can be clearly seen in the table below the plot. I don't have jupyter notebook to test this.
![image](https://github.com/facebookresearch/hiplot/assets/70601302/29eb720e-6985-4676-ae9e-1c87c8f1b54d)
Here is my code.

```python
import hiplot as hip
import pandas as pd
# example: https://github.com/facebookresearch/hiplot/tree/master/examples

# Read the CSV file into a DataFrame
df = pd.read_csv('runs.csv')
df = df.drop('params.Training time', axis=1)
# Update column names
df.rename(columns={'params.lr': 'Learning Rate', 'params.Architecture': 'Architecture', 'params.Layers': 'Layers', 'params.Relative L2 error':'Relative L2 error'}, inplace=True)
# Convert the DataFrame into a HiPlot Experiment object
experiment = hip.Experiment.from_dataframe(df)

experiment.display_data(hip.Displays.PARALLEL_PLOT).update({'hide': ['uid']})

# Export the HiPlot visualization to a standalone HTML file
experiment.to_html(file='hiplot.html')
```
Link to the HTML file: https://github.com/praksharma/temp/blob/main/ABC/hiplot.html

**Comment by danthe3rd** [comment]
Hi,
Thanks for opening this issue.
In the parallel plot, we don't display columns if they have only a single value (eg if all rows have `params.Activation="tanh"`, it won't be displayed). Can you make sure this is not the case?
