### ISSUE TITLE
Specifying which field to color by

### ISSUE THREAD

**Issue by jtuckerk** [facebookresearch/hiplot#29]
It it possible to set which field determines the colors of the lines? The first few times I used this experiments with high accuracy were read and ones with low accuracy were blue or green. This made finding useful trends stand out a bit better, but now the values of some parameter I don't care about as much determine the color and it's not as useful. Is the field chosen randomly?

**Comment by danthe3rd** [comment]
Hi,

It is not possible to specify it programmatically yet, however you can change it once the experiment is displayed. To do so, right-click on the axis label and then click "Use for coloring".

![image](https://user-images.githubusercontent.com/43445237/74634184-a7613800-5163-11ea-82bc-fa54ec296c32.png)
![image](https://user-images.githubusercontent.com/43445237/74634224-b34cfa00-5163-11ea-96a4-07148c391ee3.png)
![image](https://user-images.githubusercontent.com/43445237/74634257-bf38bc00-5163-11ea-9ed3-a6aacef26a2f.png)

**Comment by jtuckerk** [comment]
perfect! Thank you!
This is a great tool!

Sorry if that was in the docs and I just missed it
