### ISSUE TITLE
bs4 dependencies break conda recipe

### ISSUE THREAD

**Issue by rpanai** [facebookresearch/hiplot#32]
I tried to build a conda-forge recipe for this package but i got this error for `bs4`

```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'bs4'}
```

Is it eventyally possible to change this to beautifulsoup4? As bs4 it's jus a dummy package see [this](https://pypi.org/project/bs4/).

**Comment by danthe3rd** [comment]
Hi,
Thanks for reporting! Will fix in the next version :)

**Comment by danthe3rd** [comment]
Updated in `0.1.5`
