### ISSUE TITLE
Allow users to hide 'uid' and 'from_uid' from the table

### ISSUE THREAD

**Issue by kamil-kaczmarek** [facebookresearch/hiplot#34]
Hi @danthe3rd,

Thanks for the nice library. Very lightweight, very useful :slightly_smiling_face:

**Background**
When I have a lot of axes on the parallel plot I always drop `uid` and `from_uid` axes, because they add some unnecessary clutter to the chart. I still want to keep these two axes in the table.
In my case I have other axes than encode runs.

**Request**
Add an option (maybe to the display function) to not display `uid` and `from_uid` axes on the chart.

Best,
Kamil

**Comment by danthe3rd** [comment]
Hi,

There is a `hide` setting you can use to hide columns in the parallel plot. You can have a look here for an example: https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings

I hope this helps :)

**Comment by kamil-kaczmarek** [comment]
Hey @danthe3rd,

Yes, it solved my problem, thank you.

**Comment by bensdm** [comment]
Is it possible to hide on parallel plot but display on the table below?

**Comment by danthe3rd** [comment]
> Is it possible to hide on parallel plot but display on the table below?

All the columns are always displayed on the table. The `hide` setting only refers to the parallel plot part.

**Comment by bensdm** [comment]
indeed sorry i made a typo in my code, but is is possible to hide from uid in the columns?

**Comment by danthe3rd** [comment]
Not yet no. Maybe in a future version :)

**Comment by haw230** [comment]
Just wanted to add I would like this change too! It would make the table a lot cleaner to be able to drop uid and from_uid.

**Comment by danthe3rd** [comment]
Reopening to track it

**Comment by danthe3rd** [comment]
I've just pushed `0.1.19` (you can upgrade with `pip install -U hiplot`), which adds support for hiding columns in the table.

The documentation contains an example: https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings. You can now add this to hide the `uid` and `from_uid` columns:
```python
exp.display_data(hip.Displays.TABLE).update({
    # Don't display `uid` and `from_uid` columns to the user
    'hide': ['uid', 'from_uid'],
})
```

**Comment by kamil-kaczmarek** [comment]
Great to see this change. Thanks @danthe3rd

**Comment by Andy-Border** [comment]
Is it possible to hide the "uid" and "from_uid" in the jupyter_notebook? I'm getting the "uid" columns occasionally while plotting with `hip.Experiment.from_dataframe(df).display()`
![image](https://user-images.githubusercontent.com/26394168/150742305-ddb144c2-86ab-4fa6-b7d9-76cfb134b4f2.png)

**Comment by GoldenCorgi** [comment]
@Andy-Border 

> Is it possible to hide the "uid" and "from_uid" in the jupyter_notebook? I'm getting the "uid" columns occasionally while plotting with `hip.Experiment.from_dataframe(df).display()`. See the right-most 'uid' column in the pic below.

Does this code below work for you?

```python
exp = hip.Experiment.from_dataframe(df)
exp.display_data(hip.Displays.PARALLEL_PLOT).update({'hide': ['uid']}) # Change ['uid'] to a list of column names to be hidden. E.g. ['uid', 'dropout']
exp.display()
```

Reference: https://colab.research.google.com/github/facebookresearch/hiplot/blob/main/examples/HiPlotColabExample.ipynb

Should work in Colab and other Jupyter environments

**Comment by Andy-Border** [comment]
> @Andy-Border
> 
> > Is it possible to hide the "uid" and "from_uid" in the jupyter_notebook? I'm getting the "uid" columns occasionally while plotting with `hip.Experiment.from_dataframe(df).display()`. See the right-most 'uid' column in the pic below.
> 
> Does this code below work for you?
> 
> ```python
> exp = hip.Experiment.from_dataframe(df)
> exp.display_data(hip.Displays.PARALLEL_PLOT).update({'hide': ['uid']}) # Change ['uid'] to a list of column names to be hidden. E.g. ['uid', 'dropout']
> exp.display()
> ```
> 
> Reference: https://colab.research.google.com/github/facebookresearch/hiplot/blob/main/examples/HiPlotColabExample.ipynb
> 
> Should work in Colab and other Jupyter environments
> 
> If it doesn't work, do open a new issue, I'll work on it if it's a bug!

Hi GoldenCorgi,
Thanks for your prompt reply and valuable code snippet. It worked🥂! 
Yet it would be very helpful to drop the "uid" and "from_uid" columns in the table below the plot, Q1. is there any method to achieve this?
Q2. By default, the table is sorted by the "uid", is there any method to pass a sorted_by argument to the table? (instead of manually click on the column title)🧐

![image](https://user-images.githubusercontent.com/26394168/150774981-1647d52c-fe84-46fc-906e-23d7f3dd5679.png)

**Comment by danthe3rd** [comment]
Hi :)

Yes you can do both. [The documentation is here](https://facebookresearch.github.io/hiplot/plugins_reference.html#table)

I didn't test it, but this code should work:

```python
exp = hip.Experiment.from_dataframe(df)
exp.display_data(hip.Displays.PARALLEL_PLOT).update({'hide': ['uid']}) # Change ['uid'] to a list of column names to be hidden. E.g. ['uid', 'dropout']
exp.display_data(hip.Displays.TABLE).update({'hide': ['uid']}) # Same here
exp.display_data(hip.Displays.TABLE).update({'order_by': [('lr', 'asc')]}) # Order by LR asc
exp.display()
```

**Comment by Andy-Border** [comment]
> Hi :)
> 
> Yes you can do both. [The documentation is here](https://facebookresearch.github.io/hiplot/plugins_reference.html#table)
> 
> I didn't test it, but this code should work:
> 
> ```python
> exp = hip.Experiment.from_dataframe(df)
> exp.display_data(hip.Displays.PARALLEL_PLOT).update({'hide': ['uid']}) # Change ['uid'] to a list of column names to be hidden. E.g. ['uid', 'dropout']
> exp.display_data(hip.Displays.TABLE).update({'hide': ['uid']}) # Same here
> exp.display_data(hip.Displays.TABLE).update({'order_by': [('lr', 'asc')]}) # Order by LR asc
> exp.display()
> ```

Thank you mate, this works like a charm 🤗 !
