### ISSUE TITLE
It's now possible to install via conda. Update README

### ISSUE THREAD

**Issue by rpanai** [facebookresearch/hiplot#36]
I created a conda-forge recipe and my [PR](https://github.com/conda-forge/staged-recipes/pull/10929) is merged so you can install this package with conda [link](https://anaconda.org/conda-forge/hiplot) using

```
conda install -c conda-forge hiplot
```

You might consider to update the README accordingly.

**Comment by anovember** [comment]
conda install isn't working properly for me: 

`jinja2.exceptions.TemplateNotFound: index.html`

**Comment by rpanai** [comment]
Did you receive this during installation or after a specific command?

**Comment by sesise0307** [comment]
Would you also make it available hiplot version 0.1.3 in conda-forge?
I get an error message that says "index.html" is not found when I use v0.1.5, but not v0.1.3.

**Comment by danthe3rd** [comment]
Oh actually this is a problem in the source dist.
It will be fixed in `0.1.6` - I'll deploy it in a few hours (https://github.com/facebookresearch/hiplot/pull/37)

**Comment by rpanai** [comment]
@danthe3rd the recipe is updated and should be readily available to install.
@sesise0307 Do you mind to check if the new version fix the problem? If not is still necessary to add `0.1.3`?

**Comment by sesise0307** [comment]
Hello, thanks for your rapid response.
If I use `pip`, v0.1.6 is installed and it works.
If I use `conda`, v0.1.5 is installed and it doesn't work.

I hope you update hiplot version to 0.1.6 for conda-forge as well.

**Comment by rpanai** [comment]
@sesise0307 according to [conda](https://anaconda.org/conda-forge/hiplot) the new version should be available for download. I already merged the [PR](https://github.com/conda-forge/hiplot-feedstock/pull/1) 30 minutes ago. I don't know how long it takes to then be available to be actually download it

**Comment by sesise0307** [comment]
I just re-tested, and `conda` also provides the latest version.
Thanks a lot!

**Comment by sesise0307** [comment]
@rpanai I have a new issue with `0.1.6` installed via `conda`.

```python
import hiplot as hip
data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam'},
        {'dropout':0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam'}]
hip.Experiment.from_iterable(data).display(force_full_width=True)
```
This example code yields this error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/sseo/miniconda3/envs/dragon/lib/python3.7/site-packages/hiplot/static/icon.png'
```

If I install `hiplot` via `pip`, it works though.

**Comment by rpanai** [comment]
@sesise0307 I just opened an [issue](https://github.com/conda-forge/hiplot-feedstock/issues/2)

**Comment by danthe3rd** [comment]
Yes indeed now it's another missing file that I forgot ... Pushing `0.1.7` to fix that - sorry for the trouble

**Comment by rpanai** [comment]
@danthe3rd now the error is 
```
FileNotFoundError: [Errno 2] No such file or directory: '~/.conda/envs/hiplot/lib/python3.7/site-packages/hiplot/static/built/hiplot.bundle.js'
```

**Comment by danthe3rd** [comment]
Indeed, should be fixed in `0.1.7.post1`. Added an automated test for both the wheel and sdist to ensure we don't have this problem again in the future...

**Comment by mayur29** [comment]
Hi,

I have python 3.7.3 on my mac . When i install this via pip , I get following error

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement hiplot (from versions: none)
ERROR: No matching distribution found for hiplot

Can someone help

Thanks
Mayur Sand

**Comment by danthe3rd** [comment]
Hi @mayur29 
This seems unrelated to the current issue. But it might be because your `pip` is outdated. The latest version of pip (`pip --version`) for now is `20.0.2`. You may want to update it with `pip install -U pip`, or see https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494#49748494.
Then you can follow this guide to install hiplot in a virtualenv (https://facebookresearch.github.io/hiplot/getting_started.html#python-virtualenv).

**Comment by mayur29** [comment]
Thank you , my pip version was latest but i did not create virtualenv . Now its working for me

**Comment by sesise0307** [comment]
@rpanai @danthe3rd Now, it works perfectly. Thank you so much!

**Comment by rpanai** [comment]
@sesise0307 Thank you to promptly report issues. 
@danthe3rd given that the package is now on [conda-feedstock](https://github.com/conda-forge/conda-feedstock) so everytime there is an update on this repos I need just to accept an automatic PR. If you want me to add as a maintainer of this recipe just ask.

**Comment by danthe3rd** [comment]
> @sesise0307 Thank you to promptly report issues.
> @danthe3rd given that the package is now on [conda-feedstock](https://github.com/conda-forge/conda-feedstock) so everytime there is an update on this repos I need just to accept an automatic PR. If you want me to add as a maintainer of this recipe just ask.

Thank you for everything you did! Yes please can you add me as well? I'll also add the information about conda install in the doc+readme

**Comment by rpanai** [comment]
> Thank you for everything you did! Yes please can you add me as well? I'll also add the information about conda install in the doc+readme


@danthe3rd  done! [meta.yaml](https://github.com/conda-forge/hiplot-feedstock/blob/master/recipe/meta.yaml)

**Comment by danthe3rd** [comment]
Just updated the README to include the conda link. Thank you!
