### ISSUE TITLE
Use search result as filter

### ISSUE THREAD

**Issue by bensdm** [facebookresearch/hiplot#41]
Hey, is there a way to use search result as a filter for the parallel plots?

Thanks

**Comment by danthe3rd** [comment]
Hey :)
Yup, sounds like a cool feature to have - will add this to the next release in a few weeks

**Comment by danthe3rd** [comment]
Sorry for the late follow-up - this has been merged into master, and will be added to the next version (`0.1.8`)
https://github.com/facebookresearch/hiplot/pull/49
