### ISSUE TITLE
AttributeError: module 'hiplot' has no attribute 'Experiment'

### ISSUE THREAD

**Issue by ramsjha** [facebookresearch/hiplot#42]
AttributeError: module 'hiplot' has no attribute 'Experiment' with version __version__ = "0.1.7.post2". is there any issue

**Comment by danthe3rd** [comment]
Hi,

First, I'm sorry you're having issues using HiPlot. Did you install it with `pip install hiplot`?
Can you try `import hiplot; print(hiplot.__file__)` to see which module it is loading? If you have a folder named `hiplot` there can be conflicts.

Thank you

**Comment by LodewijkBrand** [comment]
I had a similar issue. But I accidentally called my tester `.py` file: `hiplot.py`. Changing the name fixed the issue.

**Comment by danthe3rd** [comment]
Thank you for the feedback @LodewijkBrand. Since I don't see any further message from the original poster, I will close this issue.
