### ISSUE TITLE
Get selection ranges

### ISSUE THREAD

**Issue by DavidWalz** [facebookresearch/hiplot#46]
Is there a way to query the selected ranges from the parallel coordinates plots?

And thanks publishing HiPlot! Having a parallel coordinates plot for selecting data as a drop-in in ipython notebooks is really usefull.

**Comment by danthe3rd** [comment]
Hi :)

It is currently not possible to retrieve the selected *ranges* from the parallel coordinates plot. However, it is possible to retrieve the selected *rows*, but with the following limitations:
- it only works on Jupyter notebooks
- you have to retrieve the selected rows in a different cell than the one that created the HiPlot rendering

```python
# First notebook cell
import hiplot as hip
data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam'},
        {'dropout':0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam'}]
h = hip.Experiment.from_iterable(data).display()

# Second cell, after HiPlot from above has loaded
selected_datapoints = h.get_selected() # List of hiplot.Datapoint
[dp.values for dp in selected_datapoints] # List of dicts
```

Does it help in your use-case?

**Comment by DavidWalz** [comment]
That's quick response :) Well, comparing the selected datapoints with the entire dataframe its possible to estimate the selected ranges. It would be nice to query the actual ranges from the plot as is possible in plotly's parcoord plot (which in contrast does not allow to query the selected datapoints).
I'm asking because with the selection ranges the user expresses a preference which is useful for planning new experiments in iterative aproach.

**Comment by danthe3rd** [comment]
Oh I see, makes sense :) I'll see how I can implement it in a future version

**Comment by danthe3rd** [comment]
Will be implemented in https://github.com/facebookresearch/hiplot/pull/52, and added to the next upcoming version `0.1.8`

**Comment by danthe3rd** [comment]
Added in `0.1.8` and documented here: https://facebookresearch.github.io/hiplot/tuto_notebook.html#interactions-with-displayed-visualization
