### ISSUE TITLE
Bools are converted to NaN

### ISSUE THREAD

**Issue by jtuckerk** [facebookresearch/hiplot#47]
True and False are both converted to NaN in the inline display and in a saved html plot in version 0.1.7.post3 

```
import hiplot as hip
print(hip.__version__)
l = [{'a': 0, 'b':'hey', 'c':False},
     {'a': 0, 'b':'hey2', 'c':True},
]
exp_vis = hip.Experiment.from_iterable(l)
html = exp_vis.to_html('/tmp/hiplot.html')
exp_vis.display()
```

![hiplotnan](https://user-images.githubusercontent.com/8518434/78400704-137ceb80-75ac-11ea-959e-e4732be0db75.png)

edited: added version

**Comment by danthe3rd** [comment]
Hi :)
Thanks for the bug report. It'll be fixed in the next version with this change (https://github.com/facebookresearch/hiplot/pull/51).
