### ISSUE TITLE
Change color map used for coloring

### ISSUE THREAD

**Issue by Mbompr** [facebookresearch/hiplot#62]
Hi,
Thanks for this very powerful library.

In my use case, the best and worst experiments are not very easy to distinguish with the default color map. Indeed, the best (very dark blue) and the worst (very dark red) look similar.
I am thus looking for a way to use a custom colormap (such as one available in matplotlib https://matplotlib.org/tutorials/colors/colormaps.html) that would suit better my use case.

I did not find any easy way to do so. It feels that using a custom [ValueDef](https://github.com/facebookresearch/hiplot/blob/b8b3277e21b92464a10d63be31259faf6ce4e37e/hiplot/experiment.py#L58) might be a way to go. However, it does not look the right way to go, especially since the color I want to use for coloring of continuous type and ValueDef asks for a dictionary that should provide a color for each possible value.

Is there anyway to specify the color map to be used? Otherwise, is it possible to assign manually a color to each experiment (and in such a case manually assign the right one from the colormap). I have tried adding `'c': 'black'` as in https://facebookresearch.github.io/hiplot/py_reference.html#hiplot-experiment but it does not work.

Thanks

**Comment by danthe3rd** [comment]
Hi @Mbompr 

Thank you for your feedback.
There is indeed no way to change the color map currently. I'll add the possibility to change the colormap into any d3 colormap (https://github.com/d3/d3-scale-chromatic) - I'll keep you updated.

Best
