### ISSUE TITLE
ascending sort - uid

### ISSUE THREAD

**Issue by kmavropou** [facebookresearch/hiplot#70]
Hello. I just want to ask you if I can change the default sort order for uid in HiPlot. I saw that when I visualise my exp as a default there is a sorting into uid and into Dataframe that I am insert into Hiplot. I don't want to make changes by clicking the uid after plot come up. I just want to make changes that by default the plot starts with ascending order. Is this possible? 
Thank you. :)

**Comment by danthe3rd** [comment]
Hi @kmavropou and thank you for the feedback :)
Can you provide an extract of the code you use to render in hiplot?
Also, you mention the order in HiPlot: do you mean the order of the rows in the table below, or do you mean the order in the parallel plot?
Thank you!

**Comment by kmavropou** [comment]
` hip.Experiment().from_dataframe(df1).display()`

- I have one dataftame df1 with the fields Ranking and Ranking_2 as you can see in my plot. 
<img width="997" alt="hiplot" src="https://user-images.githubusercontent.com/16328078/80787690-e19d7b80-8b8f-11ea-8966-ac6fcd9fc83b.png">
The uid in plot is on top 5 and in bottom 1. I want as a default to change this order in plot not in the rows.  I know that the plot is interactive and I can change this by clicking the uid in plot, but I am wondering if I can change this default ordering rule without clicking.
- Also, can I pass two dataframes in my experiment? I saw that you can pass two datapoints.
Thank you 🙏

**Comment by danthe3rd** [comment]
Something like this should work for you :)
```
import hiplot as hip
# Merge experiments from df1 and df2
hiplot_experiment = hip.Experiment.merge({
    'df1': hip.Experiment.from_dataframe(df1),
    'df2': hip.Experiment.from_dataframe(df2),
})
# Update rendering settings - see also https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings
hiplot_experiment.display_data(hip.Displays.PARALLEL_PLOT).update({
    'invert': ['uid']
})
# Display as usual
hiplot_experiment.display()
```

**Comment by kmavropou** [comment]
Perfect. Thank you for your help.
