### ISSUE TITLE
Font size in output

### ISSUE THREAD

**Issue by gaetandebacker** [facebookresearch/hiplot#85]
Dear,

This library is proving very useful for visualisations in my master's thesis on hyperparameter optimisation. I was wondering if there would be a way to be able to increase the font sizes of the axis labels, such that they are more readable when I include screenshots of them in my report.

Kind regards

**Comment by danthe3rd** [comment]
Hi @gaetandebacker 

First, thank you for the feedback :)
Are you using the webserver/standalone HTML or do you embed hiplot in a notebook?

In the first case, you can use `Cmd/Ctrl and "+"` and `Cmd/Ctrl and "-"` to change the zoom level in your browser (https://support.google.com/chrome/answer/96810). Then you can reduce the height of the parallel plot to get something like this
![image](https://user-images.githubusercontent.com/43445237/83019052-96f40f80-a026-11ea-8e0f-c1e9ff4b57a1.png)

Best

**Comment by gaetandebacker** [comment]
Hi @danthe3rd ,

Thanks for your reply. I am using it in a notebook. I was not aware that I could reduce the height of the parallel plot after zooming. Now it is working fine!

**Comment by danthe3rd** [comment]
HiPlot is not really meant to do beautiful plots tho, more for exploring and playing with data at this point - but I'm glad that it worked for you :)
I'm closing the issue, but let me know if there is anything else we can improve!
